/* eslint-disable no-unused-vars */
import React, {useState} from 'react'
import { useNavigate } from 'react-router-dom'
import { preview } from '../assets'
import {getRandomPrompt} from '../utils'
import {Form , Loader} from '../components'

const CreatePost = () => {

    const navigate = useNavigate()
    const [form, setForm] = useState({
        name:'',
        prompt:'',
        photo:'',

    })

    const [generateImg, setGenerateImg] = useState(false)
    const [loading, setLoading] = useState(false)
    const [generatingImg, setGeneratingImg] = useState(false)
    const generateImage = async () => {
        if(form.prompt){
            try {
            setGeneratingImg(true)

            const response = await fetch("http://localhost:8080/api/v1/dalle", {
                method: "POST",
                headers: {
                "Content-Type": "application/json",
                },
                body: JSON.stringify({prompt: form.prompt})
            });
            const data = await response.json()
            setForm({...form, photo: `data:image/jpeg;base64,${data.photo}`})
         } catch(error){
            console.log('Error while generating image: ', error);
            alert('Error while generating image');
         } finally {
            setGeneratingImg(false);

         }
        } else {
            alert('Please enter a prompt');
        }
    }
    

    const handleSubmit = async(e) => {
        e.preventDefault();

        if(form.prompt && form.photo){
            setLoading(true)
            try{
                const response = await fetch('http://localhost:8080/api/v1/post', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify(form)
                });

                await response.json()
                navigate('/');
            } catch(error){
                alert(error);
                console.log('Error while creating post: ', error);
            }finally{
                setLoading(false);
            }      
        } 
    }
    const handleChange = (e) => {
        e.preventDefault();
        setForm({...form, [e.target.name]: e.target.value})
    }
    const handleSurpriseMe = () => {
        const randomPrompt = getRandomPrompt(form.prompt)
        setForm({...form, prompt: randomPrompt})
    }

  return (
    <section className='max-w-7xl mx-auto'>
        <div>
            <h1 className='font-extrabold text-[#222328] text-[32px]'>Create</h1>
            <p className="mt-2 text-[#666e75] text-[14px] max-w-[500px]">Create imaginative and visually stunning images generated by DALL-E AI and share them with the community</p>
            
        </div>
        <form className='mt-16 max-w-3xl' onSubmit={handleSubmit}>
        <div className='flex flex-col gap-5'>
            <Form 
                labelName='Your Name'
                type='text'
                name='name'
                placeholder='Jan Doe'
                value={form.name}
                handleChange={handleChange}
            />
            
            <Form 
                labelName='Prompt'
                type='text'
                name='prompt'
                placeholder='Two futuristic towers with a skybridge covered in lush foliage, digital art'
                value={form.prompt}
                handleChange={handleChange}
                isSurpriseMe
                handleSurpriseMe={handleSurpriseMe}
            />
            <div className='relative bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-l focus:rinf-blue-500 focus:border-blue-500 w-64 p-3 h-64 flex justify-center items-center'>
                    {form.photo ? (
                        <img src={form.photo} alt={form.prompt} className='w-full h-full object-contain' />
                    ) : (
                        <img src={preview} alt='preview' className= 'w-9/12 h-9/12 object-contain opacity-40' />
                    )}

                    {generatingImg && ( 
                        <div className='absolute inset-0 z-0 bg-black bg-opacity-60 flex justify-center items-center'>
                            <Loader />
                        </div>
                    )}
            </div>
        </div>
        <div className='mt-5 flex gap-5 '>
            <button
                type='button'
                onClick={generateImage}
                className='bg-[#6469ff] text-white font-medium px-6 py-2 rounded-md hover:bg-[#4b4fbb] focus:outline-none focus:ring-2 focus:ring-[#6469ff] focus:ring-opacity-50'
            >
                {generatingImg ? 'Generating Image...' : 'Generate Image'}
            </button>

        </div>

        <div className='mt-10'>
            <p className='mt-2 text-[#666e75] text-[14px]'>
                Alright you got your artistic image ready, now show it to the world!!!!
            </p>
        </div>
        <button type='submit' className='mt-3 text-white bg-[#6469ff] font-medium rounded-md text-sm w-full sm:w-auto px-5 py-2.5 text-center'>
            {loading ? 'Sharing Post Rigth Now...' : 'Create Post'}
        </button>
        </form>
    </section>
  )
}


export default CreatePost;